name: Makefile CI

on:
  push:
    branches: [ action-test ]
  pull_request:
    branches: [ action-test ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: arm-none-eabi-gcc
      uses: fiam/arm-none-eabi-gcc@v1.0.2
      with:
        release: 9-2019-q4     
    - name: dependencies
      run:  cd ./software && ./download_dependencies.sh && cd -
      
    - name: Build TX
      run: cd ./spftware/tx && make -j 8 && cd -
    
    - name: Build RX
      run: cd ./spftware/rx && make -j 8 && cd -
